import streamlit as st
import plotly.express as px
from reportlab.lib import styles
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from utils.constants import (
    TOP_TRANSACTIONS_LIMIT
)

from reportlab.lib import colors

from reportlab.lib.styles import (
    getSampleStyleSheet
)
styles = getSampleStyleSheet()

from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle

from reportlab.platypus import Image
from reportlab.platypus import KeepTogether

import matplotlib.pyplot as plt

import pandas as pd

from datetime import datetime

from reportlab.lib.units import inch

brand_style = ParagraphStyle(

    "BrandTitle",

    parent=styles["Title"],

    textColor=colors.darkblue,

    fontSize=28,

    leading=34

)

def add_pdf_metadata(canvas, doc):

    canvas.setTitle(
        "FinSight AI Financial Report"
    )

    canvas.setAuthor(
        "FinSight AI"
    )

    canvas.setSubject(
        "Personal Finance Analytics Report"
    )

    canvas.setCreator(
        "FinSight AI Platform"
    )

    canvas.drawString(

        inch,

        0.5 * inch,

        "Generated by FinSight AI"

    )

    canvas.drawRightString(

        7.5 * inch,

        0.5 * inch,

        f"Page {doc.page}"

    )

def generate_financial_report(

    filename,

    df,

    total_income,
    total_expense,
    total_savings,

    stability_score,

    savings_component,
    budget_component,
    volatility_component,
    anomaly_component

):

    doc = SimpleDocTemplate(
        filename
    )

    styles = (
        getSampleStyleSheet()
    )

    elements = []

    # ==========================================
    # COVER PAGE
    # ==========================================

    elements.append(

        Spacer(
            1,
            120
        )

    )

    logo = Image(
        "assets/Finsight Logo.png",
        width=550,
        height=200
    )

    elements.append(logo)


    elements.append(

        Paragraph(

            "AI-Powered Personal Finance Analytics & Forecasting Platform",

            styles["Heading2"]

        )

    )

    elements.append(
        Spacer(1, 40)
    )

    elements.append(

        Paragraph(

            f"Generated on: "
            f"{datetime.now().strftime('%d-%m-%Y %H:%M')}",

            styles["Normal"]

        )

    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(

        Paragraph(

            "Confidential Financial Analytics Report",

            styles["Normal"]

        )

    )

    from reportlab.platypus import PageBreak

    elements.append(
        PageBreak()
    )

    # ==========================================
    # TITLE
    # ==========================================

    elements.append(

        Paragraph(
            "FinSight AI Financial Report",
            styles["Title"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(

        Paragraph(

            f"Generated on: "
            f"{datetime.now().strftime('%d-%m-%Y %H:%M')}",

            styles["Normal"]

        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================================
    # SUMMARY TABLE
    # ==========================================

    report_data = [

        [
            "Metric",
            "Value"
        ],

        [
            "Total Income",
            f"Rs. {total_income:,.2f}"
        ],

        [
            "Total Expense",
            f"Rs. {total_expense:,.2f}"
        ],

        [
            "Total Savings",
            f"Rs. {total_savings:,.2f}"
        ],

        [
            "Financial Stability Score",
            f"{stability_score}/100"
        ]
    ]

    table = Table(
        report_data,
        colWidths=[200, 200]
    )

    table.setStyle(

        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.lightgrey
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                1,
                colors.black
            ),

            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),

            (
                "ALIGN",
                (0, 0),
                (-1, -1),
                "CENTER"
            )
        ])
    )

    elements.append(
        table
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================================
    # EXECUTIVE SUMMARY
    # ==========================================

    elements.append(

        Paragraph(
            "Executive Summary",
            styles["Heading2"]
        )

    )

    if total_income > 0:

        savings_rate = (
            total_savings /
            total_income
        ) * 100

    else:

        savings_rate = 0

    summary_text = (

        f"During this reporting period, total income was "
        f"Rs. {total_income:,.2f}, while total expenses were "
        f"Rs. {total_expense:,.2f}. "

        f"The resulting savings amounted to "
        f"Rs. {total_savings:,.2f}, producing a savings rate of "
        f"{savings_rate:.1f}%."

    )

    elements.append(

        Paragraph(
            summary_text,
            styles["Normal"]
        )

    )

    elements.append(
        Spacer(1, 20)
    )

    category_chart_path = None
    trend_path = None
    stability_chart = None

    # ==========================================
    # EXPENSE DISTRIBUTION CHART
    # ==========================================

    if not df.empty:

        expense_by_category = (
            df.groupby("Category")["Amount"]
            .sum()
            .sort_values(ascending=True)
            .reset_index()
        )

        fig = px.bar(

            expense_by_category,

            x="Amount",

            y="Category",

            orientation="h",

            title="Expense Distribution by Category",

            text="Amount"

        )

        fig.update_traces(
            texttemplate="₹%{x:,.0f}",
            textposition="inside"
        )

        fig.update_layout(
            height=550,
            margin=dict(
                l=80,
                r=80,
                t=60,
                b=60
            )
        )

        category_chart_path = (
            "expense_distribution.png"
        )

        fig.write_image(
            category_chart_path
        )

        elements.append(

            KeepTogether([

                Paragraph(
                    "Expense Distribution",
                    styles["Heading2"]
                ),

                Spacer(1, 10),

                Image(
                    category_chart_path,
                    width=420,
                    height=280
                ),

                Spacer(1, 20)

            ])

        )
            
        
    # ==========================================
    # MONTHLY EXPENSE TREND
    # ==========================================

    if not df.empty:

        trend_df = df.copy()

        trend_df["Date"] = pd.to_datetime(
            trend_df["Date"]
        )

        monthly_expense = (

            trend_df

            .groupby(
                trend_df["Date"]
                .dt.to_period("M")
            )["Amount"]

            .sum()

            .reset_index()

        )

        monthly_expense["Date"] = (
            monthly_expense["Date"]
            .astype(str)
        )

        plt.figure(
            figsize=(6, 4)
        )

        plt.plot(

            monthly_expense["Date"],

            monthly_expense["Amount"],

            marker="o"

        )

        plt.title(
            "Monthly Expense Trend"
        )

        plt.xlabel(
            "Month"
        )

        plt.ylabel(
            "Expense"
        )

        plt.tight_layout()

        trend_path = (
            "monthly_trend.png"
        )

        plt.savefig(
            trend_path
        )

        plt.close()

        elements.append(

            KeepTogether([

                Paragraph(

                    "Monthly Expense Trend",

                    styles["Heading2"]

                ),

                Spacer(1, 10),

                Image(

                    trend_path,

                    width=350,

                    height=220

                ),

                Spacer(1, 20)

            ])
        )

    # ==========================================
    # FINANCIAL STABILITY
    # ==========================================

    elements.append(

        Paragraph(
            "Financial Stability Assessment",
            styles["Heading2"]
        )
    )

    if stability_score >= 80:

        health_Stability = (
            "Excellent Financial Stability"
        )

    elif stability_score >= 60:

        health_Stability = (
            "Moderate Financial Stability"
        )

    else:

        health_Stability = (
            "Financial Stability Needs Improvement"
        )

    elements.append(

        Paragraph(
            health_Stability,
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================================
    # SAVINGS ANALYSIS
    # ==========================================

    if total_income > 0:

        savings_rate = (
            total_savings /
            total_income
        ) * 100

    else:

        savings_rate = 0

    elements.append(

        Paragraph(
            "Savings Analysis",
            styles["Heading2"]
        )
    )

    elements.append(

        Paragraph(
            f"Savings Rate: {savings_rate:.1f}%",
            styles["Normal"]
        )
    )

    if savings_rate >= 20:

        elements.append(

            Paragraph(
                "Savings target achieved.",
                styles["Normal"]
            )
        )

    else:

        elements.append(

            Paragraph(
                "Savings below recommended 20% level.",
                styles["Normal"]
            )
        )

    # ==========================================
    # TOP SPENDING CATEGORIES
    # ==========================================

    elements.append(

        Paragraph(
            "Top Spending Categories",
            styles["Heading2"]
        )

    )

    if not df.empty:

        top_categories = (

            df.groupby("Category")["Amount"]
            .sum()
            .sort_values(
                ascending=False
            )
            .head(TOP_TRANSACTIONS_LIMIT)

        )

    else:

        top_categories = pd.Series(
            dtype=float
        )

    category_data = [

        [
            "Category",
            "Amount"
        ]

    ]

    for category, amount in top_categories.items():

        category_data.append(

            [
                category,
                f"Rs. {amount:,.2f}"
            ]

        )

    category_table = Table(
        category_data,
        colWidths=[200, 200]
    )

    category_table.setStyle(

        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.lightgrey
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                1,
                colors.black
            ),

            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            )

        ])

    )

    elements.append(
        category_table
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================================
    # STABILITY SCORE BREAKDOWN
    # ==========================================

    components = [

        "Savings",
        "Budget",
        "Volatility",
        "Anomaly"

    ]

    scores = [

        savings_component,
        budget_component,
        volatility_component,
        anomaly_component

    ]

    plt.figure(
        figsize=(6, 4)
    )

    plt.bar(
        components,
        scores
    )

    plt.title(
        "Stability Score Breakdown"
    )

    plt.ylabel(
        "Score"
    )

    plt.tight_layout()

    stability_chart = (
        "stability_breakdown.png"
    )

    plt.savefig(
        stability_chart
    )

    plt.close()

    elements.append(

        KeepTogether([

            Paragraph(

                "Stability Score Breakdown",

                styles["Heading2"]

            ),

            Spacer(1, 10),

            Image(

                stability_chart,

                width=300,
                height=180

            ),

            Spacer(1, 10),

            Paragraph(

                f"Overall Stability Score: {stability_score}/100",

                styles["Normal"]

            ),

            Spacer(1, 20)

        ])
    )
    # ==========================================
    # AI RECOMMENDATIONS
    # ==========================================

    elements.append(

        Paragraph(
            "AI Financial Recommendations",
            styles["Heading2"]
        )

    )

    recommendations = []

    if savings_rate < 20:

        recommendations.append(
            "Increase monthly savings to at least 20% of income."
        )

    if total_expense > total_income:

        recommendations.append(
            "Reduce discretionary spending to avoid overspending."
        )

    top_category = (

        df.groupby("Category")["Amount"]
        .sum()
        .sort_values(
            ascending=False
        )
        .index[0]

    )

    recommendations.append(
        f"Monitor spending in '{top_category}' as it is your highest expense category."
    )

    if savings_rate >= 30:

        recommendations.append(
            "Excellent saving behavior. Maintain current spending habits."
        )

    for rec in recommendations:

        elements.append(

            Paragraph(
                f"• {rec}",
                styles["Normal"]
            )

        )

    elements.append(
        Spacer(1, 20)
    )
    # ==========================================
    # BUILD PDF
    # ==========================================

    doc.build(

    elements,

    onFirstPage=
    add_pdf_metadata,

    onLaterPages=
    add_pdf_metadata

)
    
    import os

    if os.path.exists(category_chart_path):
        os.remove(category_chart_path)

    if os.path.exists(trend_path):
        os.remove(trend_path)

    if os.path.exists(stability_chart):
        os.remove(stability_chart)